image: "hseeberger/scala-sbt:11.0.4_1.3.3_2.13.1"

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy -Dsbt.coursier.home=sbt-cache/coursier"
  COURSIER_CACHE: sbt-cache/coursier

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - "sbt-cache/sbtboot"
    - "sbt-cache/boot"
    - "sbt-cache/ivy/cache"
    - "sbt-cache/coursier"

stages:
  - test

test:
  script:
    - sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck test
