# Create a TODO
POST http://127.0.0.1:8080/todo
Content-Type: application/json

{
  "title": "Do laundry",
  "completed": false
}

###

# List TODOs
GET http://127.0.0.1:8080/todo

###

# Get specific TODO
GET http://127.0.0.1:8080/todo/c17809d9-9880-4f9b-9102-5c0629bcaf33

###
